"""scale_fields

Revision ID: 379d83e43a70
Revises: e9dae5430e40
Create Date: 2026-09-18 12:12:03.145467
"""
from alembic import op
import sqlalchemy as sa


revision = '379d83e43a70'
down_revision = 'e9dae5430e40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_counters',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('next_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.add_column('runs', sa.Column('worker_id', sa.String(length=64), nullable=True))
    op.add_column('runs', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('cancel_requested', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'cancel_requested')
    op.drop_column('runs', 'heartbeat_at')
    op.drop_column('runs', 'worker_id')
    op.drop_table('ticket_counters')
    # ### end Alembic commands ###
