"""run_preapproved

Revision ID: 4068384371ec
Revises: 379d83e43a70
Create Date: 2026-09-18 13:23:10.178117
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4068384371ec'
down_revision = '379d83e43a70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('data_vectors_768_embedding_idx'), table_name='data_vectors_768', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('vectors_768_idx_1'), table_name='data_vectors_768')
    op.drop_index(op.f('vectors_768_idx_kind_text'), table_name='data_vectors_768')
    op.drop_index(op.f('vectors_768_idx_project_id_text'), table_name='data_vectors_768')
    op.drop_table('data_vectors_768')
    op.add_column('runs', sa.Column('preapproved', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'preapproved')
    op.create_table('data_vectors_768',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_vectors_768_pkey'))
    )
    op.create_index(op.f('vectors_768_idx_project_id_text'), 'data_vectors_768', [sa.literal_column("((metadata_ ->> 'project_id'::text)::character varying)")], unique=False)
    op.create_index(op.f('vectors_768_idx_kind_text'), 'data_vectors_768', [sa.literal_column("((metadata_ ->> 'kind'::text)::character varying)")], unique=False)
    op.create_index(op.f('vectors_768_idx_1'), 'data_vectors_768', [sa.literal_column("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    op.create_index(op.f('data_vectors_768_embedding_idx'), 'data_vectors_768', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
