"""embed_provider

Revision ID: e9dae5430e40
Revises: aac6ed0da5e7
Create Date: 2026-09-18 12:06:50.791527
"""
from alembic import op
import sqlalchemy as sa


revision = 'e9dae5430e40'
down_revision = 'aac6ed0da5e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('embed_provider', sa.String(length=20), nullable=False))
    op.add_column('user_settings', sa.Column('embed_base_url', sa.String(length=255), nullable=True))
    op.add_column('user_settings', sa.Column('embed_api_key_enc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'embed_api_key_enc')
    op.drop_column('user_settings', 'embed_base_url')
    op.drop_column('user_settings', 'embed_provider')
    # ### end Alembic commands ###
