/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectsSlugRouteImport } from './routes/_app/projects/$slug'
import { Route as AppProjectsNewRouteImport } from './routes/_app/projects/new'
import { Route as AppProjectsSlugIndexRouteImport } from './routes/_app/projects/$slug/index'
import { Route as AppProjectsSlugActivityRouteImport } from './routes/_app/projects/$slug/activity'
import { Route as AppProjectsSlugApprovalsRouteImport } from './routes/_app/projects/$slug/approvals'
import { Route as AppProjectsSlugFilesRouteImport } from './routes/_app/projects/$slug/files'
import { Route as AppProjectsSlugGraphRouteImport } from './routes/_app/projects/$slug/graph'
import { Route as AppProjectsSlugIntegrationsRouteImport } from './routes/_app/projects/$slug/integrations'
import { Route as AppProjectsSlugKnowledgeRouteImport } from './routes/_app/projects/$slug/knowledge'
import { Route as AppProjectsSlugMemoryRouteImport } from './routes/_app/projects/$slug/memory'
import { Route as AppProjectsSlugSettingsRouteImport } from './routes/_app/projects/$slug/settings'
import { Route as AppProjectsSlugTasksRouteImport } from './routes/_app/projects/$slug/tasks'
import { Route as AppProjectsSlugTicketsRouteImport } from './routes/_app/projects/$slug/tickets'
import { Route as AppProjectsSlugAgentsIndexRouteImport } from './routes/_app/projects/$slug/agents.index'
import { Route as AppProjectsSlugAgentsAgentIdRouteImport } from './routes/_app/projects/$slug/agents.$agentId'
import { Route as AppProjectsSlugRunsIndexRouteImport } from './routes/_app/projects/$slug/runs.index'
import { Route as AppProjectsSlugRunsRunIdRouteImport } from './routes/_app/projects/$slug/runs.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSlugRoute = AppProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsSlugIndexRoute = AppProjectsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsSlugRoute,
} as any)
const AppProjectsSlugActivityRoute = AppProjectsSlugActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppProjectsSlugRoute,
} as any)
const AppProjectsSlugApprovalsRoute =
  AppProjectsSlugApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AppProjectsSlugRoute,
  } as any)
const AppProjectsSlugFilesRoute = AppProjectsSlugFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppProjectsSlugRoute,
} as any)
const AppProjectsSlugGraphRoute = AppProjectsSlugGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppProjectsSlugRoute,
} as any)
const AppProjectsSlugIntegrationsRoute =
  AppProjectsSlugIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AppProjectsSlugRoute,
  } as any)
const AppProjectsSlugKnowledgeRoute =
  AppProjectsSlugKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AppProjectsSlugRoute,
  } as any)
const AppProjectsSlugMemoryRoute = AppProjectsSlugMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppProjectsSlugRoute,
} as any)
const AppProjectsSlugSettingsRoute = AppProjectsSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppProjectsSlugRoute,
} as any)
const AppProjectsSlugTasksRoute = AppProjectsSlugTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppProjectsSlugRoute,
} as any)
const AppProjectsSlugTicketsRoute = AppProjectsSlugTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppProjectsSlugRoute,
} as any)
const AppProjectsSlugAgentsIndexRoute =
  AppProjectsSlugAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AppProjectsSlugRoute,
  } as any)
const AppProjectsSlugAgentsAgentIdRoute =
  AppProjectsSlugAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AppProjectsSlugRoute,
  } as any)
const AppProjectsSlugRunsIndexRoute =
  AppProjectsSlugRunsIndexRouteImport.update({
    id: '/runs/',
    path: '/runs/',
    getParentRoute: () => AppProjectsSlugRoute,
  } as any)
const AppProjectsSlugRunsRunIdRoute =
  AppProjectsSlugRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => AppProjectsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/projects/$slug': typeof AppProjectsSlugRouteWithChildren
  '/projects/new': typeof AppProjectsNewRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$slug/activity': typeof AppProjectsSlugActivityRoute
  '/projects/$slug/approvals': typeof AppProjectsSlugApprovalsRoute
  '/projects/$slug/files': typeof AppProjectsSlugFilesRoute
  '/projects/$slug/graph': typeof AppProjectsSlugGraphRoute
  '/projects/$slug/integrations': typeof AppProjectsSlugIntegrationsRoute
  '/projects/$slug/knowledge': typeof AppProjectsSlugKnowledgeRoute
  '/projects/$slug/memory': typeof AppProjectsSlugMemoryRoute
  '/projects/$slug/settings': typeof AppProjectsSlugSettingsRoute
  '/projects/$slug/tasks': typeof AppProjectsSlugTasksRoute
  '/projects/$slug/tickets': typeof AppProjectsSlugTicketsRoute
  '/projects/$slug/': typeof AppProjectsSlugIndexRoute
  '/projects/$slug/agents/$agentId': typeof AppProjectsSlugAgentsAgentIdRoute
  '/projects/$slug/runs/$runId': typeof AppProjectsSlugRunsRunIdRoute
  '/projects/$slug/agents/': typeof AppProjectsSlugAgentsIndexRoute
  '/projects/$slug/runs/': typeof AppProjectsSlugRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/activity': typeof AppActivityRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$slug/activity': typeof AppProjectsSlugActivityRoute
  '/projects/$slug/approvals': typeof AppProjectsSlugApprovalsRoute
  '/projects/$slug/files': typeof AppProjectsSlugFilesRoute
  '/projects/$slug/graph': typeof AppProjectsSlugGraphRoute
  '/projects/$slug/integrations': typeof AppProjectsSlugIntegrationsRoute
  '/projects/$slug/knowledge': typeof AppProjectsSlugKnowledgeRoute
  '/projects/$slug/memory': typeof AppProjectsSlugMemoryRoute
  '/projects/$slug/settings': typeof AppProjectsSlugSettingsRoute
  '/projects/$slug/tasks': typeof AppProjectsSlugTasksRoute
  '/projects/$slug/tickets': typeof AppProjectsSlugTicketsRoute
  '/projects/$slug': typeof AppProjectsSlugIndexRoute
  '/projects/$slug/agents/$agentId': typeof AppProjectsSlugAgentsAgentIdRoute
  '/projects/$slug/runs/$runId': typeof AppProjectsSlugRunsRunIdRoute
  '/projects/$slug/agents': typeof AppProjectsSlugAgentsIndexRoute
  '/projects/$slug/runs': typeof AppProjectsSlugRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/projects/$slug': typeof AppProjectsSlugRouteWithChildren
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$slug/activity': typeof AppProjectsSlugActivityRoute
  '/_app/projects/$slug/approvals': typeof AppProjectsSlugApprovalsRoute
  '/_app/projects/$slug/files': typeof AppProjectsSlugFilesRoute
  '/_app/projects/$slug/graph': typeof AppProjectsSlugGraphRoute
  '/_app/projects/$slug/integrations': typeof AppProjectsSlugIntegrationsRoute
  '/_app/projects/$slug/knowledge': typeof AppProjectsSlugKnowledgeRoute
  '/_app/projects/$slug/memory': typeof AppProjectsSlugMemoryRoute
  '/_app/projects/$slug/settings': typeof AppProjectsSlugSettingsRoute
  '/_app/projects/$slug/tasks': typeof AppProjectsSlugTasksRoute
  '/_app/projects/$slug/tickets': typeof AppProjectsSlugTicketsRoute
  '/_app/projects/$slug/': typeof AppProjectsSlugIndexRoute
  '/_app/projects/$slug/agents/$agentId': typeof AppProjectsSlugAgentsAgentIdRoute
  '/_app/projects/$slug/runs/$runId': typeof AppProjectsSlugRunsRunIdRoute
  '/_app/projects/$slug/agents/': typeof AppProjectsSlugAgentsIndexRoute
  '/_app/projects/$slug/runs/': typeof AppProjectsSlugRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/activity'
    | '/dashboard'
    | '/settings'
    | '/projects/$slug'
    | '/projects/new'
    | '/projects/'
    | '/projects/$slug/activity'
    | '/projects/$slug/approvals'
    | '/projects/$slug/files'
    | '/projects/$slug/graph'
    | '/projects/$slug/integrations'
    | '/projects/$slug/knowledge'
    | '/projects/$slug/memory'
    | '/projects/$slug/settings'
    | '/projects/$slug/tasks'
    | '/projects/$slug/tickets'
    | '/projects/$slug/'
    | '/projects/$slug/agents/$agentId'
    | '/projects/$slug/runs/$runId'
    | '/projects/$slug/agents/'
    | '/projects/$slug/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/activity'
    | '/dashboard'
    | '/settings'
    | '/projects/new'
    | '/projects'
    | '/projects/$slug/activity'
    | '/projects/$slug/approvals'
    | '/projects/$slug/files'
    | '/projects/$slug/graph'
    | '/projects/$slug/integrations'
    | '/projects/$slug/knowledge'
    | '/projects/$slug/memory'
    | '/projects/$slug/settings'
    | '/projects/$slug/tasks'
    | '/projects/$slug/tickets'
    | '/projects/$slug'
    | '/projects/$slug/agents/$agentId'
    | '/projects/$slug/runs/$runId'
    | '/projects/$slug/agents'
    | '/projects/$slug/runs'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/activity'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/projects/$slug'
    | '/_app/projects/new'
    | '/_app/projects/'
    | '/_app/projects/$slug/activity'
    | '/_app/projects/$slug/approvals'
    | '/_app/projects/$slug/files'
    | '/_app/projects/$slug/graph'
    | '/_app/projects/$slug/integrations'
    | '/_app/projects/$slug/knowledge'
    | '/_app/projects/$slug/memory'
    | '/_app/projects/$slug/settings'
    | '/_app/projects/$slug/tasks'
    | '/_app/projects/$slug/tickets'
    | '/_app/projects/$slug/'
    | '/_app/projects/$slug/agents/$agentId'
    | '/_app/projects/$slug/runs/$runId'
    | '/_app/projects/$slug/agents/'
    | '/_app/projects/$slug/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$slug': {
      id: '/_app/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof AppProjectsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$slug/': {
      id: '/_app/projects/$slug/'
      path: '/'
      fullPath: '/projects/$slug/'
      preLoaderRoute: typeof AppProjectsSlugIndexRouteImport
      parentRoute: typeof AppProjectsSlugRoute
    }
    '/_app/projects/$slug/activity': {
      id: '/_app/projects/$slug/activity'
      path: '/activity'
      fullPath: '/projects/$slug/activity'
      preLoaderRoute: typeof AppProjectsSlugActivityRouteImport
      parentRoute: typeof AppProjectsSlugRoute
    }
    '/_app/projects/$slug/approvals': {
      id: '/_app/projects/$slug/approvals'
      path: '/approvals'
      fullPath: '/projects/$slug/approvals'
      preLoaderRoute: typeof AppProjectsSlugApprovalsRouteImport
      parentRoute: typeof AppProjectsSlugRoute
    }
    '/_app/projects/$slug/files': {
      id: '/_app/projects/$slug/files'
      path: '/files'
      fullPath: '/projects/$slug/files'
      preLoaderRoute: typeof AppProjectsSlugFilesRouteImport
      parentRoute: typeof AppProjectsSlugRoute
    }
    '/_app/projects/$slug/graph': {
      id: '/_app/projects/$slug/graph'
      path: '/graph'
      fullPath: '/projects/$slug/graph'
      preLoaderRoute: typeof AppProjectsSlugGraphRouteImport
      parentRoute: typeof AppProjectsSlugRoute
    }
    '/_app/projects/$slug/integrations': {
      id: '/_app/projects/$slug/integrations'
      path: '/integrations'
      fullPath: '/projects/$slug/integrations'
      preLoaderRoute: typeof AppProjectsSlugIntegrationsRouteImport
      parentRoute: typeof AppProjectsSlugRoute
    }
    '/_app/projects/$slug/knowledge': {
      id: '/_app/projects/$slug/knowledge'
      path: '/knowledge'
      fullPath: '/projects/$slug/knowledge'
      preLoaderRoute: typeof AppProjectsSlugKnowledgeRouteImport
      parentRoute: typeof AppProjectsSlugRoute
    }
    '/_app/projects/$slug/memory': {
      id: '/_app/projects/$slug/memory'
      path: '/memory'
      fullPath: '/projects/$slug/memory'
      preLoaderRoute: typeof AppProjectsSlugMemoryRouteImport
      parentRoute: typeof AppProjectsSlugRoute
    }
    '/_app/projects/$slug/settings': {
      id: '/_app/projects/$slug/settings'
      path: '/settings'
      fullPath: '/projects/$slug/settings'
      preLoaderRoute: typeof AppProjectsSlugSettingsRouteImport
      parentRoute: typeof AppProjectsSlugRoute
    }
    '/_app/projects/$slug/tasks': {
      id: '/_app/projects/$slug/tasks'
      path: '/tasks'
      fullPath: '/projects/$slug/tasks'
      preLoaderRoute: typeof AppProjectsSlugTasksRouteImport
      parentRoute: typeof AppProjectsSlugRoute
    }
    '/_app/projects/$slug/tickets': {
      id: '/_app/projects/$slug/tickets'
      path: '/tickets'
      fullPath: '/projects/$slug/tickets'
      preLoaderRoute: typeof AppProjectsSlugTicketsRouteImport
      parentRoute: typeof AppProjectsSlugRoute
    }
    '/_app/projects/$slug/agents/': {
      id: '/_app/projects/$slug/agents/'
      path: '/agents'
      fullPath: '/projects/$slug/agents/'
      preLoaderRoute: typeof AppProjectsSlugAgentsIndexRouteImport
      parentRoute: typeof AppProjectsSlugRoute
    }
    '/_app/projects/$slug/agents/$agentId': {
      id: '/_app/projects/$slug/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/projects/$slug/agents/$agentId'
      preLoaderRoute: typeof AppProjectsSlugAgentsAgentIdRouteImport
      parentRoute: typeof AppProjectsSlugRoute
    }
    '/_app/projects/$slug/runs/': {
      id: '/_app/projects/$slug/runs/'
      path: '/runs'
      fullPath: '/projects/$slug/runs/'
      preLoaderRoute: typeof AppProjectsSlugRunsIndexRouteImport
      parentRoute: typeof AppProjectsSlugRoute
    }
    '/_app/projects/$slug/runs/$runId': {
      id: '/_app/projects/$slug/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/projects/$slug/runs/$runId'
      preLoaderRoute: typeof AppProjectsSlugRunsRunIdRouteImport
      parentRoute: typeof AppProjectsSlugRoute
    }
  }
}

interface AppProjectsSlugRouteChildren {
  AppProjectsSlugActivityRoute: typeof AppProjectsSlugActivityRoute
  AppProjectsSlugApprovalsRoute: typeof AppProjectsSlugApprovalsRoute
  AppProjectsSlugFilesRoute: typeof AppProjectsSlugFilesRoute
  AppProjectsSlugGraphRoute: typeof AppProjectsSlugGraphRoute
  AppProjectsSlugIntegrationsRoute: typeof AppProjectsSlugIntegrationsRoute
  AppProjectsSlugKnowledgeRoute: typeof AppProjectsSlugKnowledgeRoute
  AppProjectsSlugMemoryRoute: typeof AppProjectsSlugMemoryRoute
  AppProjectsSlugSettingsRoute: typeof AppProjectsSlugSettingsRoute
  AppProjectsSlugTasksRoute: typeof AppProjectsSlugTasksRoute
  AppProjectsSlugTicketsRoute: typeof AppProjectsSlugTicketsRoute
  AppProjectsSlugIndexRoute: typeof AppProjectsSlugIndexRoute
  AppProjectsSlugAgentsAgentIdRoute: typeof AppProjectsSlugAgentsAgentIdRoute
  AppProjectsSlugRunsRunIdRoute: typeof AppProjectsSlugRunsRunIdRoute
  AppProjectsSlugAgentsIndexRoute: typeof AppProjectsSlugAgentsIndexRoute
  AppProjectsSlugRunsIndexRoute: typeof AppProjectsSlugRunsIndexRoute
}

const AppProjectsSlugRouteChildren: AppProjectsSlugRouteChildren = {
  AppProjectsSlugActivityRoute: AppProjectsSlugActivityRoute,
  AppProjectsSlugApprovalsRoute: AppProjectsSlugApprovalsRoute,
  AppProjectsSlugFilesRoute: AppProjectsSlugFilesRoute,
  AppProjectsSlugGraphRoute: AppProjectsSlugGraphRoute,
  AppProjectsSlugIntegrationsRoute: AppProjectsSlugIntegrationsRoute,
  AppProjectsSlugKnowledgeRoute: AppProjectsSlugKnowledgeRoute,
  AppProjectsSlugMemoryRoute: AppProjectsSlugMemoryRoute,
  AppProjectsSlugSettingsRoute: AppProjectsSlugSettingsRoute,
  AppProjectsSlugTasksRoute: AppProjectsSlugTasksRoute,
  AppProjectsSlugTicketsRoute: AppProjectsSlugTicketsRoute,
  AppProjectsSlugIndexRoute: AppProjectsSlugIndexRoute,
  AppProjectsSlugAgentsAgentIdRoute: AppProjectsSlugAgentsAgentIdRoute,
  AppProjectsSlugRunsRunIdRoute: AppProjectsSlugRunsRunIdRoute,
  AppProjectsSlugAgentsIndexRoute: AppProjectsSlugAgentsIndexRoute,
  AppProjectsSlugRunsIndexRoute: AppProjectsSlugRunsIndexRoute,
}

const AppProjectsSlugRouteWithChildren = AppProjectsSlugRoute._addFileChildren(
  AppProjectsSlugRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppProjectsSlugRoute: typeof AppProjectsSlugRouteWithChildren
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppProjectsSlugRoute: AppProjectsSlugRouteWithChildren,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
